### ISSUE TITLE
will this angular picker work on angular 4 and 5

### ISSUE THREAD

**Issue by saravananNV** [zhaber/ng-bootstrap-datetimepicker#142]
##### Bug description:
will this angular datetime picker work on angular 4 or 5

**Comment by zhaber** [comment]
Adding support for Angular 5 is planned to be done by January.

**Comment by zhaber** [comment]
An alpha version was published to npm. See http://plnkr.co/edit/FH9QBCHaloCqGz9Qrd85?p=preview
