### ISSUE TITLE
making the datetimepicker dirty does not make the form dirty

### ISSUE THREAD

**Issue by bishtpradeep** [zhaber/ng-bootstrap-datetimepicker#143]
##### Bug description:
when the form is loaded for the first time, everything works as expected. 
But once the form is marked pristine (e.g, submit button is clicked), then changing the datetimepicker does not mark the form dirty again.

##### Link to minimally-working plunker that reproduces the issue: 
http://plnkr.co/edit/Q0Tx0r291v7qwaxivIZs?p=preview
Thank you.

**Comment by zhaber** [comment]
Fixed in the new ng-bootstrap component (based on Angular 5 and Bootstrap 4).
