### ISSUE TITLE
Datetimepicker component is not compatible with Angular AoT (Ahead-of-time) compilation.

### ISSUE THREAD

**Issue by mmorsky** [zhaber/ng-bootstrap-datetimepicker#145]
Hi,

We're using the datetimepicker component in our application and it works nicely in our test/develop environment. However, when we try to deploy to production, or more specifically, try to use the [Angular AoT feature](https://angular.io/guide/aot-compiler#the-ahead-of-time-aot-compiler), we get problems.

The problem seems to be that the component template uses some properties which are declared private (`onDateChange` and `onTimeChange`). This causes the build to fail when using the `--aot` flag, eg. `ng build --aot`

This is documented quite shortly and perhaps not so clearly in the [docs](https://angular.io/guide/aot-compiler#phase-2-code-generation).

I think this is a known issue in Angular, at least there's a lot of discussion on the subject on bug reports on the project, for example [this one](https://github.com/angular/angular/issues/11978). 

Have you ran into the same problem before? Or do you know if there's someway to solve this issue on our side (other than disabling the AoT)?

**Comment by zhaber** [comment]
I've removed private access modifier for now

**Comment by mmorsky** [comment]
Great, thanks a lot for the quick fix! 
Do you have plans to publish this to npm soon, or how we could deploy this fixed version easily?

**Comment by zhaber** [comment]
Published a new npm version
